[project]
name = "blog"
version = "0.1.0"
description = "a simple blog api"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-rest-auth>=7.2.0",
    "django>=6.0.5",
    "django-allauth>=65.17.0",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.17.1",
    "requests>=2.34.2",
]

















